name: Create Snapshot

on:
  workflow_dispatch:
  pull_request:

jobs:
  create-snapshot-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get images
        id: get-images
        uses: trifork/cheetah-infrastructure-utils/.github/actions/docker/get-images@main
        with:
          image-name: cheetah-infrastructure-utils-kafka
          TRIFORK_GITHUB_PAT: ${{ secrets.WRITE_PACKAGE_PAT }}

      - name: Get version
        id: get-version
        uses: trifork/cheetah-infrastructure-utils-workflows/.github/actions/versioning/get-version@main
        with:
          file-path: Dockerfile
          prefix: 'LABEL version=\"'
          suffix: '\"'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3

      - name: Get package suffix
        id: get-package-suffix
        run: echo "branch-name=$(echo '${{ github.ref_name }}' | sed 's/[^a-zA-Z0-9]/-/g')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        id: build-image
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/trifork/cheetah-infrastructure-utils-kafka:${{ steps.get-version.outputs.version }}-${{ steps.get-package-suffix.outputs.branch-name }}-SNAPSHOT-${{ github.run_number }}
          push: true