name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
      version:
        description: The full version for the release branch. This should be strimzi-x.y.z-kafka-x.y.z-trifork-x.y.z
        required: true
        type: string

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.READ_PACKAGE_PAT }}

      - name: Bump docker version
        run: sed -i 's/LABEL version="[^"]*"/LABEL version="${{ inputs.version }}"/' Dockerfile

      - name: Bump maven version
        run: mvn build-helper:parse-version versions:set -DgenerateBackupPoms=false -DnewVersion=${{ inputs.version }}

      - name: Create release branch
        run: |
          git config user.name "cheetahbot"
          git config user.email "cheetahbot@users.noreply.github.com"

          git checkout -b release/${{ inputs.version }}

      - name: Commit release branch creation
        id: commit-branch
        uses: qoomon/actions--create-commit@v1
        with:
          message: "Create new release branch release/${{ inputs.version }}"
          allow-empty: true

      - name: Create release branch
        run: |
          git push --set-upstream origin release/${{ inputs.version }}

          git checkout ${{ github.ref_name }}
          git merge release/${{ inputs.version }}
          git push
