name: Create Snapshot

on:
  workflow_dispatch:

jobs:
  verify-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: "Success"
        if: ${{ startsWith(github.ref_name, 'release/') }}
        run: |
          echo "Creating a release candidate for branch '${{ github.ref_name }}'"
          exit 0

      - name: "Error"
        if: ${{ !startsWith(github.ref_name, 'release/') }}
        run: |
          echo "::error::Cannot create release candidate from branch '${{ github.ref_name }}' since it does not start with 'release/'"
          exit 1

  create-release-candidate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version
        id: get-version
        uses: trifork/cheetah-infrastructure-utils-workflows/.github/actions/versioning/get-version@main
        with:
          file-path: Dockerfile
          prefix: 'LABEL version=\"'
          suffix: '\"'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3

      - name: Get package suffix
        id: get-package-suffix
        run: echo "branch-name=$(echo '${{ github.ref_name }}' | sed 's/[^a-zA-Z0-9]/-/g')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        id: build-image
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/trifork/cheetah-infrastructure-utils-kafka:${{ steps.get-version.outputs.version }}-${{ steps.get-package-suffix.outputs.branch-name }}-SNAPSHOT-${{ github.run_number }}
          push: true