name: generate plantuml
on:
  #pull_request:
  #  branches:    
  #    - main
  push:
    branches:
      - "**"

permissions:
  contents: write
  pull-requests: write
  actions: write
  
jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: plantuml
    steps:
    - name: checkout
      uses: actions/checkout@v5
    - name: plantuml
      id: plantuml
      uses: grassedge/generate-plantuml-action@master
      with:
        path: docs
        message: "Render PlantUML files"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}