name: Create and publish Cheetah Kafka Docker Image

on:
  workflow_dispatch:

  push:
    branches: ["main", "release/**"]
    tags:
      - "v*"
  pull_request:
    branches: ["main", "release/**"]

env:
  BASE_IMAGE: Dockerfile
  CONTEXT: .

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ inputs.settings-path }} # location for the settings.xml file
          cache: "maven"

      - name: Package with Maven
        shell: bash
        run: mvn -B package --file pom.xml

      - name: "Build and push"
        uses: trifork/cheetah-infrastructure-utils/.github/actions/build-image@main
        with:
          read_package_pat: ${{ secrets.PACKAGE_PAT }} # we need this, as GITHUB_TOKEN only have permission to its own repo
          context: ${{ env.CONTEXT }}
          image_name: ${{ github.repository }}
          github_actor: ${{ github.actor }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_run_id: ${{ github.run_id }}
          base_image: ${{ env.BASE_IMAGE }}
          push_image: true
