name: Create and publish Cheetah Kafka Docker Image

on:
  workflow_dispatch:

  push:
    branches: ["main", "release/**"]
    tags:
      - "v*"
  pull_request:
    branches: ["main", "release/**"]

env:
  BASE_IMAGE: Dockerfile
  CONTEXT: .

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: "Build and push"
        uses: trifork/cheetah-infrastructure-utils/.github/actions/build-image@main
        with:
          read_package_pat: ${{ secrets.PACKAGE_PAT }} # we need this, as GITHUB_TOKEN only have permission to its own repo
          image_name: ${{ github.repository }}
          github_actor: ${{ github.actor }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_run_id: ${{ github.run_id }}
          base_image: ${{ env.BASE_IMAGE }}
          context: ${{ env.CONTEXT }}
          push_image: true
