name: E2E

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "30 0 * * *"
  pull_request:
    branches: ["main", "release/**"]
    types:
      - labeled
      - opened
      - edited
      - ready_for_review
      - auto_merge_enabled
      - synchronize
      - reopened
  push:
    branches: ["main", "release/**"]

permissions:
  contents: read

# act workflow_dispatch -s GITHUB_TOKEN -W .github/workflows/integrationtest.yml
jobs:
  should-run: # seperate step to support ci/cd status checks
    runs-on: ubuntu-latest
    outputs:
      tag-check: ${{ steps.tag-check.outputs.value }}
      event-name-check: ${{ steps.event-name-check.outputs.value }}

    steps:
      # the pull request contains the 'e2e-test' label
      - name: Tag check
        id: tag-check
        if: ${{ contains(github.event.pull_request.labels.*.name, 'e2e-test') && !contains(github.event.pull_request.labels.*.name, 'blocked') }}
        run: echo "value=true" >> "$GITHUB_OUTPUT"

      # not started from a pull-request
      - name: Check for specific label
        id: event-name-check
        if: ${{github.event_name != 'pull_request'}}
        run: echo "value=true" >> "$GITHUB_OUTPUT"

  e2e-test:
    needs: should-run
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ needs.should-run.outputs.event-name-check == 'true' || needs.should-run.outputs.tag-check == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGE_PAT }}

      - name: "Test kafka plugin"
        shell: bash
        run: |
          docker compose pull -q
          docker compose up --build --abort-on-container-exit
        working-directory: integrationtests/
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.PACKAGE_PAT }}
          DOCKER_REGISTRY: ghcr.io/trifork/

      - name: Print logs
        if: ${{ failure() }}
        shell: bash
        working-directory: integrationtests/
        run: docker compose logs
