name: Create and publish Cheetah Kafka Docker Image

on:
  workflow_dispatch:
  schedule:
      # * is a special character in YAML so you have to quote this string
      - cron:  '30 0 * * *'
  pull_request:
    branches: ["main", "release/**"]
  push:
    branches: [ "main", "release/**" ]

jobs:
  integrationtest:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ inputs.settings-path }} # location for the settings.xml file
          cache: "maven"

      - name: Package with Maven
        shell: bash
        run: mvn -B package --file pom.xml

      - name: Log in to the Container registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGE_PAT }}

      - name: "Test kafka plugin"
        shell: bash
        run: docker compose up --build --abort-on-container-exit
        working-directory: integrationtests/
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.PACKAGE_PAT }}
          DOCKER_REGISTRY: ghcr.io/trifork/
