name: E2E

on:
  workflow_call:
  schedule:
    - cron: "0 3 * * *"
  push:
    branches: [ 'main', 'release/v**' ]
  pull_request:
    branches: [ 'main', 'release/v**' ]
    types: [ opened, synchronize, reopened, labeled ]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

# act workflow_dispatch -s GITHUB_TOKEN -W .github/workflows/integrationtest.yml
jobs:
  should-run:
    uses: trifork/cheetah-infrastructure-utils-workflows/.github/workflows/e2e-should-run.yml@main

  e2e-test:
    needs: should-run
    if: ${{ needs.should-run.outputs.should-run }}

    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.READ_PACKAGE_PAT }}
  
      - name: Checkout trifork/cheetah-development-infrastructure
        uses: actions/checkout@v5
        with:
          repository: trifork/cheetah-development-infrastructure
          token: ${{ secrets.READ_PACKAGE_PAT }}
          path: development-infrastructure
  
      - name: "Start development infrastructure"
        working-directory: development-infrastructure/
        shell: bash
        run: docker compose up keycloak keycloak-setup -d --build --quiet-pull
        env:
          DOCKER_REGISTRY: ghcr.io/trifork/

      - name: "Test kafka plugin"
        shell: bash
        run: |
          docker compose pull -q
          docker compose up --build --abort-on-container-exit
        working-directory: integrationtests/
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.READ_PACKAGE_PAT }}
          DOCKER_REGISTRY: ghcr.io/trifork/

      - name: Print logs
        if: ${{ failure() }}
        shell: bash
        working-directory: integrationtests/
        run: docker compose logs
