name: Docker Trivy Call

on:
  pull_request:

jobs:
  trivy-image-scan:
    name: Trivy Vulnerability Changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if files have changed
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            src/**
            Dockerfile
            pom.xml

      - name: Generate vulnerability changes report
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        uses: trifork/cheetah-infrastructure-utils/.github/actions/docker/trivy-vulnerability-changes-pr@main